-- Работа с RLS
-- Включаем защиту на уровне строк
ALTER TABLE app.firefighters ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.firefighters FORCE ROW LEVEL SECURITY;

ALTER TABLE app.incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.incidents FORCE ROW LEVEL SECURITY;

ALTER TABLE app.stations ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.stations FORCE ROW LEVEL SECURITY;

ALTER TABLE app.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.vehicles FORCE ROW LEVEL SECURITY;

ALTER TABLE app.equipment ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.equipment FORCE ROW LEVEL SECURITY;

ALTER TABLE app.responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.responses FORCE ROW LEVEL SECURITY;

ALTER TABLE app.shifts ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.shifts FORCE ROW LEVEL SECURITY;
